[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "18" }

[context.production.environment]
  VITE_API_URL = "https://your-api-url.com"

# For single-page applications (React)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200