[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "functions"  # Only include if using Netlify Functions

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[context.production.environment]
  VITE_SUPABASE_URL = "https://your-project-ref.supabase.co"
  VITE_SUPABASE_ANON_KEY = "your-anon-key-here"
  GENERATE_SOURCEMAP = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"