[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "functions"  # Remove if not using Netlify Functions

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[context.production]
  [context.production.environment]
    VITE_SUPABASE_URL = "https://your-project-ref.supabase.co"
    VITE_SUPABASE_ANON_KEY = "your-anon-key-here"
    GENERATE_SOURCEMAP = "false"

[context.deploy-preview]
  [context.deploy-preview.environment]
    VITE_SUPABASE_URL = "https://your-project-ref.supabase.co"
    VITE_SUPABASE_ANON_KEY = "your-anon-key-here"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://*.supabase.co; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://*.supabase.co; font-src 'self'; frame-src 'self'"