[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "functions"  # Only include if using Netlify Functions

[build.environment]
  NODE_VERSION = "18"  # Matches most Supabase-compatible versions
  NPM_FLAGS = "--legacy-peer-deps"  # Helps prevent dependency conflicts

[context.production.environment]
  VITE_SUPABASE_URL = "your-production-supabase-url"
  VITE_SUPABASE_ANON_KEY = "your-production-anon-key"
  # Enable React production mode
  VITE_MODE = "production"

[context.deploy-preview.environment]
  VITE_SUPABASE_URL = "your-preview-supabase-url"  # Different from production
  VITE_SUPABASE_ANON_KEY = "your-preview-anon-key"
  VITE_MODE = "development"

# For single-page applications (React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers (recommended)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://*.supabase.co; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://*.supabase.co;"