[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "18" }

[build.environment]
  NODE_VERSION = "18"

[context.production.environment]
  VITE_SUPABASE_URL = "your-supabase-url"
  VITE_SUPABASE_ANON_KEY = "your-anon-key"

# For single-page applications (React)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200