[build]
  command = "npm run build"
  publish = "dist"  # ✅ Vite uses 'dist' instead of 'build'
  functions = "functions"  # Remove if not using Netlify Functions

[build.environment]
  NODE_VERSION = "18"  # Matches your local version
  NPM_FLAGS = "--legacy-peer-deps"  # Helps with dependency conflicts

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200